/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Cliente;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@javax.annotation.Generated(
        value = "io.swagger.codegen.languages.SpringCodegen",
        date = "2020-09-19T14:21:55.755Z"
)

@Api(
        value = "cliente",
        description = "the cliente API"
)
@RequestMapping(value = "/bytebank-api/v1")
public interface ClienteApi {

    @ApiOperation(
            value = "cadastra cliente",
            nickname = "cadastraCliente",
            notes = "cadastra um novo cliente",
            response = Cliente.class, authorizations = {
                @Authorization(value = "BasicAuth")
            },
            tags={ "cliente", }
    )

    @ApiResponses(value = { 
        @ApiResponse(
                code = 201,
                message = "cadastro efetuado com sucesso",
                response = Cliente.class
        ),
        @ApiResponse(
                code = 400,
                message = "requisição inválida"
        ),
        @ApiResponse(
                code = 500,
                message = "erro interno no servidor"
        )
    })

    @RequestMapping(
            value = "/cliente",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST
    )
    ResponseEntity<Cliente> cadastraCliente(@ApiParam(value = "")  @Valid @RequestBody Cliente cliente_);

}
